export const FETCH_HOUSE_REQUEST = "FETCH_HOUSE_REQUEST";
export const FETCH_HOUSE_SUCCESS = "FETCH_HOUSE_SUCCESS";
export const FETCH_HOUSE_FAILURE = "FETCH_HOUSE_FAILURE";

export const FAVOURITE_REQUEST = "FAVOURITE_REQUEST";
export const FAVOURITE_SUCCESS = "FAVOURITE_SUCCESS";
export const FAVOURITE_FAILURE = "FAVOURITE_FAILURE";